## Assignment 2 Lab Question

In [ ]:
# Two source signals are given:
# S = [[1, 2],
#      [2, 1],
#      [3, 2],
#      [4, 1]]

# Mixing matrix:
# A = [[1, 2],
#      [2, 1]]

# a) Generate mixed signals (X = AS)
# b) Apply ICA to recover source signals
# c) Compare original and recovered signals


import numpy as np
from sklearn.decomposition import FastICA

S = np.array([
    [1, 2, 3, 4],
    [2, 1, 2, 1]
])

A = np.array([
    [1, 2],
    [2, 1]
])
X = np.dot(A, S)

print("Mixed Signals (X = AS):")
print(X)

ica = FastICA(n_components=2, random_state=0)
S_estimated = ica.fit_transform(X.T)  
S_estimated = S_estimated.T           

print("\nRecovered Source Signals (after ICA):")
print(S_estimated)


print("\nOriginal Source Signals:")
print(S)

print("\nRecovered Source Signals (approximate):")
print(np.round(S_estimated, 2))

Mixed Signals (X = AS):
[[5 4 7 6]
 [4 5 8 9]]

Recovered Source Signals (after ICA):
[[-1.00000066 -0.99999934  0.99999934  1.00000066]
 [ 0.99999934 -1.00000066  1.00000066 -0.99999934]]

Original Source Signals:
[[1 2 3 4]
 [2 1 2 1]]

Recovered Source Signals (approximate):
[[-1. -1.  1.  1.]
 [ 1. -1.  1. -1.]]


In [ ]:
# Dataset:
# [1 2 3 4 5
#  2 3 4 5 6
#  3 4 5 6 7]
#
# a) Build autoencoder with architecture 5 → 2 → 5
# b) Train model to reconstruct input
# c) Print encoded (compressed) representation

import numpy as np
from sklearn.neural_network import MLPRegressor

X = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7]
], dtype=float)

autoencoder = MLPRegressor(
    hidden_layer_sizes=(2,),   
    activation='relu',
    max_iter=2000,
    random_state=42
)

autoencoder.fit(X, X)
reconstructed = autoencoder.predict(X)

print("Reconstructed Output:")
print(np.round(reconstructed, 3))

W1 = autoencoder.coefs_[0]
b1 = autoencoder.intercepts_[0]

def relu(x):
    return np.maximum(0, x)

encoded_output = relu(np.dot(X, W1) + b1)

print("\nEncoded (Compressed) Representation:")
print(np.round(encoded_output, 3))

Reconstructed Output:
[[1.648 2.496 3.374 4.18  4.575]
 [2.094 3.09  4.126 5.064 5.763]
 [2.54  3.684 4.879 5.949 6.952]]

Encoded (Compressed) Representation:
[[ 0.     6.208]
 [ 0.     8.177]
 [ 0.    10.145]]


In [ ]:
# 3: Active Learning Example
# Dataset: 120 samples, 2 features
# a) Start with 10 labeled samples
# b) Train classifier
# c) Select most uncertain sample
# d) Add to labeled set
# e) Repeat for 8 iterations

import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

X, y = make_classification(n_samples=120,
                           n_features=2,
                           n_redundant=0,
                           n_informative=2,
                           n_clusters_per_class=1,
                           random_state=42)
labeled = np.arange(10)
unlabeled = np.arange(10, 120)

model = LogisticRegression()

for iteration in range(8):
    model.fit(X[labeled], y[labeled])
    probs= model.predict_proba(X[unlabeled])[:, 1]
    query = np.argmin(np.abs(probs- 0.5))
    labeled = np.append(labeled, unlabeled[query])
    unlabeled = np.delete(unlabeled, query)
    print("Iteration:", iteration+1, "| Labeled size:", len(labeled))

print("\nFinal labeled dataset size:", len(labeled))

Iteration: 1 | Labeled size: 11
Iteration: 2 | Labeled size: 12
Iteration: 3 | Labeled size: 13
Iteration: 4 | Labeled size: 14
Iteration: 5 | Labeled size: 15
Iteration: 6 | Labeled size: 16
Iteration: 7 | Labeled size: 17
Iteration: 8 | Labeled size: 18

Final labeled dataset size: 18


In [ ]:
# 4. Radial Basis Function (RBF)
# Given:
# X = [1, 3, 5]
# Centers = [2, 4]
# sigma = 1
#
# a) Compute Euclidean distance
# b) Apply Gaussian RBF
# c) Calculate hidden layer output

import numpy as np

X = np.array([1, 3, 5])
centers = np.array([2, 4])
sigma = 1.0

distance_matrix = np.array([[abs(x - c) for c in centers] for x in X])
print("Euclidean Distance Matrix:")
print(distance_matrix)

def rbf(d):
    return np.exp(-(d**2) / (2 * sigma**2))

H = rbf(distance_matrix)

print("\nHidden Layer Output Matrix (Gaussian RBF):")
print(np.round(H, 4))

Euclidean Distance Matrix:
[[1. 3.]
 [1. 1.]
 [3. 1.]]

Gaussian RBF Output (Hidden Layer Output):
[[0.6065 0.0111]
 [0.6065 0.6065]
 [0.0111 0.6065]]


In [ ]:
# 5. Apriori Algorithm
# Transactions:
# T1: {A, B}
# T2: {A, C}
# T3: {B, C}
# T4: {A, B, C}
#
# a) Generate candidate itemsets
# b) Compute support
# c) Find frequent itemsets (min support = 2)

from itertools import combinations

transactions = [
    {"A", "B"},
    {"A", "C"},
    {"B", "C"},
    {"A", "B", "C"}
]
min_support = 2  

def support_count(itemset):
    return sum(1 for t in transactions if itemset.issubset(t))

items = sorted(set().union(*transactions))
C1 = [{i} for i in items]
print("Candidate 1-itemsets (C1):")
for i in C1:
    print(i)

print("\nSupport Counts:")
support_values = {}
for item in C1:
    support_values[frozenset(item)] = support_count(item)
    print(item, ":", support_values[frozenset(item)])


L1 = [i for i in C1 if support_count(i) >= min_support]
print("\nFrequent 1-itemsets (L1):")
for i in L1:
    print(i, "Support =", support_count(i))

C2 = [set(c) for c in combinations(items, 2)]
print("\nCandidate 2-itemsets (C2):")
for c in C2:
    print(c)

L2 = [c for c in C2 if support_count(c) >= min_support]
print("\nFrequent 2-itemsets (L2):")
for c in L2:
    print(c, "Support =", support_count(c))


C3 = [set(c) for c in combinations(items, 3)]
print("\nCandidate 3-itemsets (C3):")
for c in C3:
    print(c)

L3 = [c for c in C3 if support_count(c) >= min_support]
print("\nFrequent 3-itemsets (L3):")
for c in L3:
    print(c, "Support =", support_count(c))

Candidate 1-itemsets (C1):
{'A'}
{'B'}
{'C'}

Support Counts:
{'A'} : 3
{'B'} : 3
{'C'} : 3

Frequent 1-itemsets (L1):
{'A'} Support = 3
{'B'} Support = 3
{'C'} Support = 3

Candidate 2-itemsets (C2):
{'A', 'B'}
{'A', 'C'}
{'B', 'C'}

Frequent 2-itemsets (L2):
{'A', 'B'} Support = 2
{'A', 'C'} Support = 2
{'B', 'C'} Support = 2

Candidate 3-itemsets (C3):
{'A', 'B', 'C'}

Frequent 3-itemsets (L3):


In [ ]:
# 6. ECLAT Algorithm
# Transactions:
# T1: {A, B}
# T2: {A, C}
# T3: {B, C}
#
# a) Convert to TID list
# b) Compute intersections
# c) Identify frequent itemsets (min support = 2)


transactions = [
    {"A", "B"},
    {"A", "C"},
    {"B", "C"},
    {"A", "B"},
]
min_sup = 2

tid = {}
for i, t in enumerate(transactions):
    for item in t:
        if item not in tid:
            tid[item] = set()
        tid[item].add(i)
print("TID Lists:")
for item in tid:
    print(item, ":", tid[item])


print("\nIntersections:")
AB = tid["A"] & tid["B"]
AC = tid["A"] & tid["C"]
BC = tid["B"] & tid["C"]
print("A ∩ B =", AB, "Support =", len(AB))
print("A ∩ C =", AC, "Support =", len(AC))
print("B ∩ C =", BC, "Support =", len(BC))


print("\nFrequent Itemsets:")
for item in tid:
    if len(tid[item]) >= min_sup:
        print({item}, "Support =", len(tid[item]))

pairs = {
    ("A","B"): AB,
    ("A","C"): AC,
    ("B","C"): BC
}
for pair in pairs:
    if len(pairs[pair]) >= min_sup:
        print(set(pair), "Support =", len(pairs[pair]))

TID Lists:
A : {0, 1, 3}
B : {0, 2, 3}
C : {1, 2}

Intersections:
A ∩ B = {0, 3} Support = 2
A ∩ C = {1} Support = 1
B ∩ C = {2} Support = 1

Frequent Itemsets:
{'A'} Support = 3
{'B'} Support = 3
{'C'} Support = 2
{'A', 'B'} Support = 2


In [ ]:
# 7. Bagging Algorithm (Fixed Version)
# Generate a dataset with 400 samples; 4 features
# a. Create bootstrap samples
# b. Train 10 decision tree models
# c. Perform majority voting
# d. Compute accuracy


from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score


X, y = make_classification(
    n_samples=400,
    n_features=4,
    random_state=0
)
Xtr, Xte, ytr, yte = train_test_split(
    X, y,
    test_size=0.3,
    random_state=0
)

bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),  
    n_estimators=10,                     
    bootstrap=True,                     
    random_state=0
)
bag.fit(Xtr, ytr)

y_pred = bag.predict(Xte)
accuracy = accuracy_score(yte, y_pred)

print("Bagging Accuracy:", accuracy)

Bagging Accuracy: 0.9166666666666666


In [ ]:
# 10. Boosting Algorithm
# Dataset: 400 samples, 4 features
# a) Train boosting model
# b) Increase weights for misclassified samples
# c) Combine weak learners
# d) Compare performance with Bagging

from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, BaggingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_samples=400,
    n_features=4,
    n_informative=4,
    n_redundant=0,
    random_state=42
)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

bagging_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=10,
    random_state=42
)
bagging_model.fit(X_train, y_train)
bagging_predictions = bagging_model.predict(X_test)
bagging_accuracy = accuracy_score(y_test, bagging_predictions)


boosting_model = AdaBoostClassifier(
    estimator=DecisionTreeClassifier(max_depth=1),  # weak learner
    n_estimators=10,
    random_state=42
)
boosting_model.fit(X_train, y_train)
boosting_predictions = boosting_model.predict(X_test)
boosting_accuracy = accuracy_score(y_test, boosting_predictions)

print("Bagging Accuracy :", round(bagging_accuracy * 100, 2), "%")
print("Boosting Accuracy:", round(boosting_accuracy * 100, 2), "%")

Bagging Accuracy : 90.0 %
Boosting Accuracy: 75.83 %


In [ ]:
# 11. Agent–Environment Interaction
# States: {0,1,2,3}
# Actions: {Left, Right}
# Reward: +1 for reaching goal state (3), otherwise 0
# Simulate agent movement for 10 steps
# Display state transitions

import random

states = [0, 1, 2, 3]
actions = ["Left", "Right"]
goal_state = 3
current_state = 0

print("Initial State:", current_state)
print("\nState Transitions:\n")

for step in range(10):
    action = random.choice(actions)
    if action == "Left":
        next_state = max(0, current_state - 1)
    else:
        next_state = min(3, current_state + 1)
        
    reward = 1 if next_state == goal_state else 0
    current_state = next_state

Initial State: 0

State Transitions:

Step 1: State 0 --Right--> State 1, Reward = 0
Step 2: State 1 --Left--> State 0, Reward = 0
Step 3: State 0 --Right--> State 1, Reward = 0
Step 4: State 1 --Left--> State 0, Reward = 0
Step 5: State 0 --Right--> State 1, Reward = 0
Step 6: State 1 --Left--> State 0, Reward = 0
Step 7: State 0 --Right--> State 1, Reward = 0
Step 8: State 1 --Left--> State 0, Reward = 0
Step 9: State 0 --Left--> State 0, Reward = 0
Step 10: State 0 --Left--> State 0, Reward = 0


In [ ]:
# 12. Exploration vs Exploitation
# a) Implement ε-greedy strategy with ε = 0.2
# b) Simulate action selection for 20 iterations
# c) Count exploration vs exploitation steps
# d) Print results

import random
import numpy as np

epsilon = 0.2
iterations = 20
Q_values = np.array([0.5, 0.8, 0.3])  
actions = [0, 1, 2]
exploration_count = 0
exploitation_count = 0

print("Action Selection Process:\n")
for i in range(iterations):
    if random.random() < epsilon:
        action = random.choice(actions)
        exploration_count += 1
        print(f"Iteration {i+1}: Exploration → Selected action {action}")
    else:
        action = np.argmax(Q_values)
        exploitation_count += 1
        print(f"Iteration {i+1}: Exploitation → Selected action {action}")

print("\nSummary Results 📊")
print("Total Iterations:", iterations)
print("Exploration Steps:", exploration_count)
print("Exploitation Steps:", exploitation_count)

Action Selection Process:

Iteration 1: Exploitation → Selected action 1
Iteration 2: Exploitation → Selected action 1
Iteration 3: Exploration → Selected action 2
Iteration 4: Exploitation → Selected action 1
Iteration 5: Exploitation → Selected action 1
Iteration 6: Exploration → Selected action 1
Iteration 7: Exploitation → Selected action 1
Iteration 8: Exploitation → Selected action 1
Iteration 9: Exploration → Selected action 1
Iteration 10: Exploitation → Selected action 1
Iteration 11: Exploitation → Selected action 1
Iteration 12: Exploitation → Selected action 1
Iteration 13: Exploration → Selected action 2
Iteration 14: Exploration → Selected action 0
Iteration 15: Exploitation → Selected action 1
Iteration 16: Exploitation → Selected action 1
Iteration 17: Exploitation → Selected action 1
Iteration 18: Exploitation → Selected action 1
Iteration 19: Exploration → Selected action 1
Iteration 20: Exploitation → Selected action 1

Summary Results 📊
Total Iterations: 20
Explorat

In [ ]:
# 13. Policy Representation
# a) Define deterministic policy π(s) → a
# b) Convert into stochastic policy π(s) → p(a)
# c) Show action probabilities for each state

states = [0, 1, 2, 3]
actions = ["Left", "Right"]
deterministic_policy = {
    0: "Right",
    1: "Right",
    2: "Right",
    3: "Left"
}
print("Deterministic Policy π(s) → a:\n")
for s in states:
    print(f"π({s}) = {deterministic_policy[s]}")

stochastic_policy = {}
for s in states:
    stochastic_policy[s] = {}
    chosen_action = deterministic_policy[s]
    for a in actions:
        if a == chosen_action:
            stochastic_policy[s][a] = 0.8
        else:
            stochastic_policy[s][a] = 0.2

print("\nStochastic Policy π(s) → p(a):\n")
for s in states:
    print(f"State {s}: {stochastic_policy[s]}")

Deterministic Policy π(s) → a:

π(0) = Right
π(1) = Right
π(2) = Right
π(3) = Left

Stochastic Policy π(s) → p(a):

State 0: {'Left': 0.2, 'Right': 0.8}
State 1: {'Left': 0.2, 'Right': 0.8}
State 2: {'Left': 0.2, 'Right': 0.8}
State 3: {'Left': 0.8, 'Right': 0.2}


In [ ]:
# 14. Markov Chain
# Weather states: {Sunny, Rainy}
# Transition matrix:
# P = [[0.8, 0.2],
#      [0.4, 0.6]]
#
# a) Simulate weather for 10 days
# b) Count frequency of each state
# c) Verify transition probabilities

import numpy as np

states = ["Sunny", "Rainy"]
P = np.array([
    [0.8, 0.2],  
    [0.4, 0.6]   
])

current_state = 0 
days = 10
weather_sequence = [states[current_state]]

for day in range(days - 1):
    current_state = np.random.choice([0, 1], p=P[current_state])
    weather_sequence.append(states[current_state])

print("Weather sequence for 10 days:")
print(weather_sequence)

sunny_count = weather_sequence.count("Sunny")
rainy_count = weather_sequence.count("Rainy")
print("\nState Frequency:")
print("Sunny:", sunny_count)
print("Rainy:", rainy_count)

transition_counts = {
    "Sunny->Sunny": 0,
    "Sunny->Rainy": 0,
    "Rainy->Sunny": 0,
    "Rainy->Rainy": 0
}

for i in range(len(weather_sequence)-1):
    prev_state = weather_sequence[i]
    next_state = weather_sequence[i+1]
    transition_counts[f"{prev_state}->{next_state}"] += 1

print("\nObserved Transition Counts:")
for k, v in transition_counts.items():
    print(k, ":", v)

Weather sequence for 10 days:
['Sunny', 'Sunny', 'Rainy', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny', 'Sunny']

State Frequency:
Sunny: 9
Rainy: 1

Observed Transition Counts:
Sunny->Sunny : 7
Sunny->Rainy : 1
Rainy->Sunny : 1
Rainy->Rainy : 0


In [ ]:
# 15. Markov Reward Process
# States: {S1, S2}
# Rewards: R(S1)=5, R(S2)=2
# gamma = 0.9
#
# a) Define transition probabilities
# b) Compute value function
# c) Interpret results

import numpy as np

states = ["S1", "S2"]
R = np.array([5, 2]) 
P = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])
gamma = 0.9

I = np.eye(len(states))
V = np.linalg.inv(I - gamma * P).dot(R)

print("Value Function Results:\n")
for i in range(len(states)):
    print(f"V({states[i]}) =", round(V[i], 4))

Value Function Results:

V(S1) = 38.9041
V(S2) = 34.7945


In [ ]:
# 16. Policy Evaluation
# States: {0,1,2}
# Actions: {Left, Right}
# a) Initialize V(s)=0
# b) Perform iterative policy evaluation
# c) Show updates until convergence

import numpy as np

states = [0, 1, 2]
gamma = 0.9
theta = 0.001  
V = np.zeros(len(states))

def step(state, action):
    if state == 2:
        return state, 0 
    if action == "Left":
        next_state = max(0, state - 1)
    else:
        next_state = min(2, state + 1)
    reward = 1 if next_state == 2 else 0
    return next_state, reward

actions = ["Left", "Right"]
policy_prob = 0.5
iteration = 0

while True:
    delta = 0
    new_V = V.copy()
    print(f"\nIteration {iteration+1}")

    for s in states:
        if s == 2:
            continue  

        v_old = V[s]
        v_new = 0

        for a in actions:
            next_state, reward = step(s, a)
            v_new += policy_prob * (reward + gamma * V[next_state])

        new_V[s] = v_new
        print(f"V({s}) updated from {round(v_old,4)} → {round(v_new,4)}")
        delta = max(delta, abs(v_old - v_new))

    V = new_V
    iteration += 1

    if delta < theta:
        break

print("\nFinal Converged Value Function:")
for s in states:
    print(f"V({s}) = {round(V[s],4)}")


Iteration 1
V(0) updated from 0.0 → 0.0
V(1) updated from 0.0 → 0.5

Iteration 2
V(0) updated from 0.0 → 0.225
V(1) updated from 0.5 → 0.5

Iteration 3
V(0) updated from 0.225 → 0.3263
V(1) updated from 0.5 → 0.6013

Iteration 4
V(0) updated from 0.3263 → 0.4174
V(1) updated from 0.6013 → 0.6468

Iteration 5
V(0) updated from 0.4174 → 0.4789
V(1) updated from 0.6468 → 0.6878

Iteration 6
V(0) updated from 0.4789 → 0.525
V(1) updated from 0.6878 → 0.7155

Iteration 7
V(0) updated from 0.525 → 0.5582
V(1) updated from 0.7155 → 0.7363

Iteration 8
V(0) updated from 0.5582 → 0.5825
V(1) updated from 0.7363 → 0.7512

Iteration 9
V(0) updated from 0.5825 → 0.6002
V(1) updated from 0.7512 → 0.7621

Iteration 10
V(0) updated from 0.6002 → 0.613
V(1) updated from 0.7621 → 0.7701

Iteration 11
V(0) updated from 0.613 → 0.6224
V(1) updated from 0.7701 → 0.7759

Iteration 12
V(0) updated from 0.6224 → 0.6292
V(1) updated from 0.7759 → 0.7801

Iteration 13
V(0) updated from 0.6292 → 0.6342
V(1) up

In [ ]:
# 17. Policy Improvement
# a) Use value function from Question 16
# b) Improve policy using greedy approach
# c) Show updated policy

import numpy as np

states = [0, 1, 2]
actions = ["Left", "Right"]
gamma = 0.9
V = np.array([0.405, 0.9, 0.0])

def step(state, action):
    if state == 2:
        return state, 0
    if action == "Left":
        next_state = max(0, state - 1)
    else:
        next_state = min(2, state + 1)

    reward = 1 if next_state == 2 else 0
    return next_state, reward

policy = {}
print("Greedy Policy Improvement:\n")
for s in states:
    if s == 2:
        policy[s] = "Terminal"
        continue

    action_values = {}
    for a in actions:
        next_state, reward = step(s, a)
        action_values[a] = reward + gamma * V[next_state]

    best_action = max(action_values, key=action_values.get)
    policy[s] = best_action
    print(f"State {s}: {action_values} → Best Action = {best_action}")

print("\nUpdated Greedy Policy π'(s):\n")
for s in states:
    print(f"π({s}) = {policy[s]}")

Greedy Policy Improvement:

State 0: {'Left': np.float64(0.36450000000000005), 'Right': np.float64(0.81)} → Best Action = Right
State 1: {'Left': np.float64(0.36450000000000005), 'Right': np.float64(1.0)} → Best Action = Right

Updated Greedy Policy π'(s):

π(0) = Right
π(1) = Right
π(2) = Terminal


In [ ]:
# 18. Value Iteration
# a) Initialize V(s)=0
# b) Apply Bellman optimality update
# c) Run until convergence
# d) Extract optimal policy

import numpy as np

states = [0, 1, 2]
actions = ["Left", "Right"]
gamma = 0.9
theta = 0.001 
V = np.zeros(len(states))

def step(state, action):
    if state == 2:
        return state, 0  
    if action == "Left":
        next_state = max(0, state - 1)
    else:
        next_state = min(2, state + 1)

    reward = 1 if next_state == 2 else 0
    return next_state, reward

iteration = 0
while True:
    delta = 0
    print(f"\nIteration {iteration+1}")
    for s in states:
        if s == 2:
            continue
        
        v_old = V[s]
        action_values = []
        for a in actions:
            next_state, reward = step(s, a)
            action_values.append(reward + gamma * V[next_state])

        V[s] = max(action_values)
        print(f"V({s}) updated from {round(v_old,4)} → {round(V[s],4)}")
        delta = max(delta, abs(v_old - V[s]))

    iteration += 1
    if delta < theta:
        break

policy = {}
for s in states:
    if s == 2:
        policy[s] = "Terminal"
        continue

    action_values = {}
    for a in actions:
        next_state, reward = step(s, a)
        action_values[a] = reward + gamma * V[next_state]

    best_action = max(action_values, key=action_values.get)
    policy[s] = best_action

print("\nFinal Optimal Value Function:")
for s in states:
    print(f"V({s}) = {round(V[s],4)}")

print("\nOptimal Policy:")
for s in states:
    print(f"π({s}) = {policy[s]}")


Iteration 1
V(0) updated from 0.0 → 0.0
V(1) updated from 0.0 → 1.0

Iteration 2
V(0) updated from 0.0 → 0.9
V(1) updated from 1.0 → 1.0

Iteration 3
V(0) updated from 0.9 → 0.9
V(1) updated from 1.0 → 1.0

Final Optimal Value Function:
V(0) = 0.9
V(1) = 1.0
V(2) = 0.0

Optimal Policy:
π(0) = Right
π(1) = Right
π(2) = Terminal


In [ ]:
# 19. Monte Carlo Method
# a) Generate 5 episodes of state transitions
# b) Compute returns for each episode
# c) Estimate value function using average returns

import random
import numpy as np

states = [0, 1, 2]
actions = ["Left", "Right"]
terminal_state = 2
gamma = 0.9

def step(state, action):
    if state == terminal_state:
        return state, 0
    if action == "Left":
        next_state = max(0, state - 1)
    else:
        next_state = min(2, state + 1)

    reward = 1 if next_state == terminal_state else 0
    return next_state, reward

num_episodes = 5
episodes = []
print("Generated Episodes:\n")
for ep in range(num_episodes):
    episode = []
    state = random.choice([0, 1])

    while state != terminal_state:
        action = random.choice(actions)
        next_state, reward = step(state, action)
        episode.append((state, reward))
        state = next_state

    episodes.append(episode)
    print(f"Episode {ep+1}: {episode}")

returns = {0: [], 1: []}
print("\nReturns per Episode:\n")
for episode in episodes:
    G = 0
    for t in reversed(range(len(episode))):
        state, reward = episode[t]
        G = gamma * G + reward
        returns[state].append(G)

print("Returns:", returns)

V = {}
for state in returns:
    if returns[state]:
        V[state] = np.mean(returns[state])
    else:
        V[state] = 0

V[2] = 0 
print("\nEstimated Value Function:")
for s in states:
    print(f"V({s}) = {round(V[s],4)}")

Generated Episodes:

Episode 1: [(1, 1)]
Episode 2: [(1, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1)]
Episode 3: [(1, 0), (0, 0), (0, 0), (1, 1)]
Episode 4: [(0, 0), (0, 0), (1, 0), (0, 0), (1, 1)]
Episode 5: [(1, 1)]

Returns per Episode:

Returns: {0: [0.9, 0.81, 0.7290000000000001, 0.5904900000000002, 0.9, 0.81, 0.9, 0.7290000000000001, 0.6561000000000001], 1: [1.0, 1.0, 0.6561000000000001, 0.5314410000000002, 1.0, 0.7290000000000001, 1.0, 0.81, 1.0]}

Estimated Value Function:
V(0) = 0.7805
V(1) = 0.8585
V(2) = 0


In [ ]:
# 20. Q-Learning
# States: {0,1,2}
# Actions: {Left, Right}
# alpha = 0.1
# gamma = 0.9
# Train for 20 episodes
# Print final Q-table

import numpy as np
import random

states = [0, 1, 2]
actions = ["Left", "Right"]
alpha = 0.1   
gamma = 0.9   
epsilon = 0.2 

Q = np.zeros((len(states), len(actions)))
terminal_state = 2

def step(state, action):
    if state == terminal_state:
        return state, 0
    if action == "Left":
        next_state = max(0, state - 1)
    else:
        next_state = min(2, state + 1)

    reward = 1 if next_state == terminal_state else 0
    return next_state, reward

episodes = 20
for ep in range(episodes):
    state = random.choice([0, 1])  
    while state != terminal_state:
        if random.random() < epsilon:
            action_index = random.choice([0, 1])
        else:
            action_index = np.argmax(Q[state])

        action = actions[action_index]
        next_state, reward = step(state, action)

        Q[state][action_index] = Q[state][action_index] + alpha * (
            reward + gamma * np.max(Q[next_state]) - Q[state][action_index]
        )
        state = next_state

print("Final Q-table:\n")
for s in range(len(states)):
    print(f"State {s}: Left={round(Q[s][0],4)}, Right={round(Q[s][1],4)}")

Final Q-table:

State 0: Left=0.003, Right=0.4213
State 1: Left=0.0615, Right=0.8784
State 2: Left=0.0, Right=0.0
